# ---CNN Networks---
actor_network:
  pre_torso:
    _target_: stoix.networks.torso.CNNTorso
    channel_sizes: [32, 64, 64]
    kernel_sizes: [8, 4, 3]
    strides: [4, 2, 1]
    use_layer_norm: False
    activation: relu
    channel_first: True
    hidden_sizes: [512]
  action_head:
    _target_: stoix.networks.heads.DiscreteQNetworkHead